### ISSUE TITLE
IJKMPMoviePlayerVideoDecoderErrorNotification 3210

### ISSUE THREAD

**Issue by hanleiZoro** [qq326646683/flutter_tencentplayer#119]
[I][TXCIJKPlayer.m, decoderError, 969]:IJKMPMoviePlayerVideoDecoderErrorNotification 3210, prev: 1633939160.641

**Comment by qq326646683** [comment]
s.dependency 'TXLiteAVSDK_Player', '= 8.6.10094'

发自我的iPhone


------------------ Original ------------------
From: leilei ***@***.***&gt;
Date: Tue,Oct 12,2021 0:03 PM
To: qq326646683/flutter_tencentplayer ***@***.***&gt;
Cc: qq326646683 ***@***.***&gt;, Assign ***@***.***&gt;
Subject: Re: [qq326646683/flutter_tencentplayer] IJKMPMoviePlayerVideoDecoderErrorNotification 3210 (#119)





 
我用master分支上的代码跑起来没有发现这个解码问题。 您帮忙看下flutter_tencentplayer现在使用的是哪个SuperPlayer_iOS版本。
 

 
—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by hanleiZoro** [comment]
我看腾讯iOS版本最新的已经更新到9.2版本了，flutter_tencentplayer 插件有更新的打算么？
![image](https://user-images.githubusercontent.com/38712031/136900126-6ff02dd4-ea84-47ad-b844-8872fb06bde7.png)

**Comment by qq326646683** [comment]
腾讯播放器sdk升级到最新了-->2.0.0
