### ISSUE TITLE
ios播放网络视频黑屏

### ISSUE THREAD

**Issue by wh19990906** [qq326646683/flutter_tencentplayer#120]
### 1. 设备/系统版本:
设备iPhone6，系统版本：12.5.5
### 2. bug描述:
播放网络视频黑屏，一直显示加载中

**Comment by wh19990906** [comment]
flutter_tencentplayer升级到2.0.0了，用的作者提供的example ==> window_video_page.dart

**Comment by wh19990906** [comment]
设备iPhone6，系统版本：12.5.5，用的是插件example下 ==> window_video_page.dar， full_video_page.dart这两个demo。不知道是不是手机加载慢卡顿的原因。

**Comment by qq326646683** [comment]
你试一下0.3.0版本，这个版本我们线上用户多，没人反馈过



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: wh19990906 ***@***.***&gt;
发送时间: 2021年10月18日 16:00
收件人: qq326646683/flutter_tencentplayer ***@***.***&gt;
抄送: qq326646683 ***@***.***&gt;, Assign ***@***.***&gt;
主题: 回复：[qq326646683/flutter_tencentplayer] ios播放网络视频黑屏 (#120)





   
可以播放，进度条和声音都是正常的，但是画面一直显示加载中
  
这时候视频画面有吗
  
没有画面
 
—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
